// UI Localization - All UI labels in EN/HI/MR
// Questions are stored in Supabase and handled separately

export type Language = 'EN' | 'HI' | 'MR'

export const UI_LABELS = {
  EN: {
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    download: 'Download',
    logout: 'Logout',
    login: 'Login',
    newAssessment: 'New Assessment',
    assessmentSetup: 'Assessment Setup',
    setupDescription: 'Respondent information & language selection',
    practitionerName: 'Practitioner Name',
    practitionerNamePlaceholder: 'Your name',
    respondentInformation: 'Respondent Information',
    name: 'Name',
    age: 'Age',
    gender: 'Gender',
    education: 'Education',
    occupation: 'Occupation',
    phone: 'Phone',
    city: 'City',
    state: 'State',
    country: 'Country',
    language: 'Language',
    beginAssessment: 'Begin Assessment',
    selectLanguage: 'Select Assessment Language',
    english: 'English',
    hindi: 'Hindi',
    marathi: 'Marathi',
    mppiAssessment: 'MPPI Assessment',
    mpaapAssessment: 'Manas Prakriti & Anxiety Assessment',
    section: 'Section',
    item: 'Item',
    of: 'of',
    progress: 'Progress',
    selectOption: 'Select an option',
    coreProbe: 'Core Probe',
    followUpProbes: 'Follow-up Probes',
    probe: 'Probe',
    loadingAssessment: 'Loading assessment...',
    noItems: 'No items available',
    gad7Assessment: 'GAD-7 Anxiety Assessment',
    gad7Description: 'General Anxiety Disorder Assessment',
    notAtAll: 'Not at all',
    severalDays: 'Several days',
    moreHalfDays: 'More than half the days',
    nearlyEveryDay: 'Nearly every day',
    impairmentQuestion: 'Functional Impairment',
    impairmentDescription: 'How difficult have these problems made it to do your work, take care of things at home, or get along with other people?',
    assessmentResults: 'Assessment Results',
    completedAt: 'Completed at',
    predominantManasPrakriti: 'PREDOMINANT MANAS PRAKRITI',
    percentageScore: 'Percentage Score',
    secondaryInfluence: 'Secondary Influence',
    fullSubtypeDistribution: 'Full Subtype Distribution',
    gad7AnxietyAssessment: 'GAD-7 ANXIETY ASSESSMENT',
    totalScore: 'Total Score',
    outOf: 'out of',
    severityLevel: 'Severity Level',
    functionalImpairment: 'Functional Impairment',
    downloadPdfReport: 'Download PDF Report',
    returnToDashboard: 'Return to Dashboard',
    startNewAssessment: 'Start New Assessment',
    detailedScoreBreakdown: 'Detailed Score Breakdown',
    adminManagement: 'Admin Management',
    manageItems: 'Manage assessment items, reports, and system configuration',
    mppiItems: 'MPPI Items (118)',
    gad7Items: 'GAD-7',
    sessions: 'Sessions',
    reports: 'Reports',
    settings: 'Settings',
    filters: 'Filters',
    status: 'Status',
    all: 'All',
    completed: 'Completed',
    inProgress: 'In Progress',
    abandoned: 'Abandoned',
    gad7Severity: 'GAD-7 Severity',
    minimal: 'Minimal',
    mild: 'Mild',
    moderate: 'Moderate',
    severe: 'Severe',
    fromDate: 'From Date',
    toDate: 'To Date',
    respondent: 'Respondent',
    code: 'Code',
    date: 'Date',
    prakriti: 'Prakriti',
    score: 'Score',
    severity: 'Severity',
    actions: 'Actions',
    noSessionsFound: 'No sessions found',
    showing: 'Showing',
    pdf: 'PDF',
    sessionStats: 'Session Stats',
    totalSessions: 'Total Sessions',
    inProgressSessions: 'In Progress',
    avgDuration: 'Avg Duration',
    completionRate: 'completion',
    activePercentage: '% active',
    lastSession: 'Last',
    noSessions: 'No sessions',
    prakritidistribution: 'Prakriti Distribution',
    gad7SeverityBreakdown: 'GAD-7 Severity Breakdown',
    noPrakritiData: 'No prakriti data available',
    noGad7Data: 'No GAD-7 data available',
    dataExport: 'Data Export',
    downloadCsv: 'Download CSV',
    allSessionsScores: '- All sessions + scores',
    exportToGoogleSheets: 'Export to Google Sheets',
    comingSoon: '(Coming Soon)',
    generatePdfReport: 'Generate PDF Report',
    downloadAssessmentReport: 'Download Assessment Report',
    backToResults: 'Back to Results',
    generatingReport: 'Generating report...',
    generatingReports: 'Generating reports...',
    adminLogin: 'Admin Login',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter your username',
    enterPassword: 'Enter your password',
    loginFailed: 'Login failed',
    invalidCredentials: 'Invalid credentials',
    loading: 'Loading...',
    saving: 'Saving...',
    exporting: 'Exporting...',
    starting: 'Starting...',
    error: 'Error',
    failedToLoad: 'Failed to load',
    failedToSave: 'Failed to save',
    tryAgain: 'Try again',
    sattvika: 'Sattvika',
    rajasika: 'Rajasika',
    tamasika: 'Tamasika',
  },

  HI: {
    next: 'आगे',
    previous: 'पिछला',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    view: 'देखें',
    download: 'डाउनलोड करें',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    newAssessment: 'नया आकलन',
    assessmentSetup: 'आकलन सेटअप',
    setupDescription: 'उत्तरदाता की जानकारी और भाषा का चयन',
    practitionerName: 'चिकित्सक का नाम',
    practitionerNamePlaceholder: 'आपका नाम',
    respondentInformation: 'उत्तरदाता की जानकारी',
    name: 'नाम',
    age: 'आयु',
    gender: 'लिंग',
    education: 'शिक्षा',
    occupation: 'व्यवसाय',
    phone: 'फोन',
    city: 'शहर',
    state: 'राज्य',
    country: 'देश',
    language: 'भाषा',
    beginAssessment: 'आकलन शुरू करें',
    selectLanguage: 'आकलन भाषा चुनें',
    english: 'अंग्रेजी',
    hindi: 'हिंदी',
    marathi: 'मराठी',
    mppiAssessment: 'मानस प्रकृति आकलन',
    mpaapAssessment: 'मानस प्रकृति और चिंता आकलन',
    section: 'खंड',
    item: 'आइटम',
    of: 'का',
    progress: 'प्रगति',
    selectOption: 'एक विकल्प चुनें',
    coreProbe: 'मुख्य प्रश्न',
    followUpProbes: 'अनुवर्ती प्रश्न',
    probe: 'प्रश्न',
    loadingAssessment: 'आकलन लोड हो रहा है...',
    noItems: 'कोई आइटम उपलब्ध नहीं',
    gad7Assessment: 'GAD-7 चिंता आकलन',
    gad7Description: 'सामान्य चिंता विकार आकलन',
    notAtAll: 'बिल्कुल नहीं',
    severalDays: 'कई दिन',
    moreHalfDays: 'आधे से अधिक दिन',
    nearlyEveryDay: 'लगभग हर दिन',
    impairmentQuestion: 'कार्यात्मक बाधा',
    impairmentDescription: 'इन समस्याओं ने काम करने, घर के काम संभालने या दूसरों के साथ मिलने में कितनी कठिनाई पैदा की है?',
    assessmentResults: 'आकलन परिणाम',
    completedAt: 'पूरा किया गया',
    predominantManasPrakriti: 'प्रधान मानस प्रकृति',
    percentageScore: 'प्रतिशत स्कोर',
    secondaryInfluence: 'द्वितीयक प्रभाव',
    fullSubtypeDistribution: 'पूर्ण उप-प्रकार वितरण',
    gad7AnxietyAssessment: 'GAD-7 चिंता आकलन',
    totalScore: 'कुल स्कोर',
    outOf: 'का',
    severityLevel: 'गंभीरता स्तर',
    functionalImpairment: 'कार्यात्मक बाधा',
    downloadPdfReport: 'PDF रिपोर्ट डाउनलोड करें',
    returnToDashboard: 'डैशबोर्ड पर लौटें',
    startNewAssessment: 'नया आकलन शुरू करें',
    detailedScoreBreakdown: 'विस्तृत स्कोर विश्लेषण',
    adminManagement: 'प्रशासन प्रबंधन',
    manageItems: 'आकलन आइटम, रिपोर्ट और सिस्टम कॉन्फ़िगरेशन प्रबंधित करें',
    mppiItems: 'MPPI आइटम (118)',
    gad7Items: 'GAD-7',
    sessions: 'सेशन',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    filters: 'फ़िल्टर',
    status: 'स्थिति',
    all: 'सभी',
    completed: 'पूर्ण',
    inProgress: 'चल रहा है',
    abandoned: 'परित्यक्त',
    gad7Severity: 'GAD-7 गंभीरता',
    minimal: 'न्यूनतम',
    mild: 'हल्का',
    moderate: 'मध्यम',
    severe: 'गंभीर',
    fromDate: 'तारीख से',
    toDate: 'तारीख तक',
    respondent: 'उत्तरदाता',
    code: 'कोड',
    date: 'तारीख',
    prakriti: 'प्रकृति',
    score: 'स्कोर',
    severity: 'गंभीरता',
    actions: 'क्रियाएं',
    noSessionsFound: 'कोई सेशन नहीं मिला',
    showing: 'दिखा रहा है',
    pdf: 'PDF',
    sessionStats: 'सेशन सांख्यिकी',
    totalSessions: 'कुल सेशन',
    inProgressSessions: 'चल रहे हैं',
    avgDuration: 'औसत अवधि',
    completionRate: 'पूरा होना',
    activePercentage: '% सक्रिय',
    lastSession: 'अंतिम',
    noSessions: 'कोई सेशन नहीं',
    prakritidistribution: 'प्रकृति वितरण',
    gad7SeverityBreakdown: 'GAD-7 गंभीरता विश्लेषण',
    noPrakritiData: 'कोई प्रकृति डेटा उपलब्ध नहीं',
    noGad7Data: 'कोई GAD-7 डेटा उपलब्ध नहीं',
    dataExport: 'डेटा निर्यात',
    downloadCsv: 'CSV डाउनलोड करें',
    allSessionsScores: '- सभी सेशन + स्कोर',
    exportToGoogleSheets: 'Google Sheets में निर्यात करें',
    comingSoon: '(जल्द आ रहा है)',
    generatePdfReport: 'PDF रिपोर्ट जेनरेट करें',
    downloadAssessmentReport: 'आकलन रिपोर्ट डाउनलोड करें',
    backToResults: 'परिणामों पर वापस जाएं',
    generatingReport: 'रिपोर्ट बनाई जा रही है...',
    generatingReports: 'रिपोर्ट बनाई जा रही हैं...',
    adminLogin: 'प्रशासक लॉगिन',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    enterUsername: 'अपना उपयोगकर्ता नाम दर्ज करें',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    loginFailed: 'लॉगिन विफल',
    invalidCredentials: 'अमान्य क्रेडेंशियल',
    loading: 'लोड हो रहा है...',
    saving: 'सहेजा जा रहा है...',
    exporting: 'निर्यात किया जा रहा है...',
    starting: 'शुरू हो रहा है...',
    error: 'त्रुटि',
    failedToLoad: 'लोड करने में विफल',
    failedToSave: 'सहेजने में विफल',
    tryAgain: 'फिर से कोशिश करें',
    sattvika: 'सात्विक',
    rajasika: 'राजसिक',
    tamasika: 'तामसिक',
  },

  MR: {
    next: 'पुढे',
    previous: 'मागे',
    submit: 'सबमिट करा',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    delete: 'हटवा',
    edit: 'संपादन करा',
    view: 'पाहा',
    download: 'डाउनलोड करा',
    logout: 'लॉगआउट',
    login: 'लॉगिन',
    newAssessment: 'नवीन मूल्यांकन',
    assessmentSetup: 'मूल्यांकन सेटअप',
    setupDescription: 'उत्तरदाता माहिती आणि भाषा निवड',
    practitionerName: 'चिकित्सकाचे नाव',
    practitionerNamePlaceholder: 'आपले नाव',
    respondentInformation: 'उत्तरदाता माहिती',
    name: 'नाव',
    age: 'वय',
    gender: 'लिंग',
    education: 'शिक्षा',
    occupation: 'व्यवसाय',
    phone: 'फोन',
    city: 'शहर',
    state: 'राज्य',
    country: 'देश',
    language: 'भाषा',
    beginAssessment: 'मूल्यांकन सुरु करा',
    selectLanguage: 'मूल्यांकन भाषा निवडा',
    english: 'इंग्रजी',
    hindi: 'हिंदी',
    marathi: 'मराठी',
    mppiAssessment: 'मानस प्रकृती मूल्यांकन',
    mpaapAssessment: 'मानस प्रकृती आणि चिंता मूल्यांकन',
    section: 'विभाग',
    item: 'वस्तु',
    of: 'च',
    progress: 'प्रगती',
    selectOption: 'एक पर्याय निवडा',
    coreProbe: 'मुख्य प्रश्न',
    followUpProbes: 'अनुवर्ती प्रश्न',
    probe: 'प्रश्न',
    loadingAssessment: 'मूल्यांकन लोड होत आहे...',
    noItems: 'कोणतीही वस्तू उपलब्ध नाही',
    gad7Assessment: 'GAD-7 चिंता मूल्यांकन',
    gad7Description: 'सामान्य चिंता विकार मूल्यांकन',
    notAtAll: 'अजिबात नाही',
    severalDays: 'काही दिवस',
    moreHalfDays: 'अर्धापेक्षा जास्त दिवस',
    nearlyEveryDay: 'जवळजवळ दररोज',
    impairmentQuestion: 'कार्यात्मक दुर्बलता',
    impairmentDescription: 'या समस्यांनी काम करणे, घरचे काम संभाळणे किंवा इतरांसोबत राहणे कितपत कठीण केले आहे?',
    assessmentResults: 'मूल्यांकन परिणाम',
    completedAt: 'पूर्ण झाले',
    predominantManasPrakriti: 'प्रमुख मानस प्रकृती',
    percentageScore: 'टक्केवारी स्कोर',
    secondaryInfluence: 'दुय्यम प्रभाव',
    fullSubtypeDistribution: 'संपूर्ण उप-प्रकार वितरण',
    gad7AnxietyAssessment: 'GAD-7 चिंता मूल्यांकन',
    totalScore: 'एकूण स्कोर',
    outOf: 'च',
    severityLevel: 'तीव्रता स्तर',
    functionalImpairment: 'कार्यात्मक दुर्बलता',
    downloadPdfReport: 'PDF अहवाल डाउनलोड करा',
    returnToDashboard: 'डॅशबोर्डवर परत या',
    startNewAssessment: 'नवीन मूल्यांकन सुरु करा',
    detailedScoreBreakdown: 'तपशीलवार स्कोर विश्लेषण',
    adminManagement: 'प्रशासन व्यवस्थापन',
    manageItems: 'मूल्यांकन वस्तू, अहवाल आणि प्रणाली कॉन्फिगरेशन व्यवस्थापित करा',
    mppiItems: 'MPPI वस्तू (118)',
    gad7Items: 'GAD-7',
    sessions: 'सेशन',
    reports: 'अहवाल',
    settings: 'सेटिंग्ज',
    filters: 'फिल्टर',
    status: 'स्थिती',
    all: 'सर्व',
    completed: 'पूर्ण',
    inProgress: 'चालू',
    abandoned: 'सोडले',
    gad7Severity: 'GAD-7 तीव्रता',
    minimal: 'किमान',
    mild: 'हलका',
    moderate: 'मध्यम',
    severe: 'गंभीर',
    fromDate: 'तारखेपासून',
    toDate: 'तारखेपर्यंत',
    respondent: 'उत्तरदाता',
    code: 'कोड',
    date: 'तारीख',
    prakriti: 'प्रकृती',
    score: 'स्कोर',
    severity: 'तीव्रता',
    actions: 'कृत्ये',
    noSessionsFound: 'कोणतेही सेशन आढळले नाही',
    showing: 'दर्शविते',
    pdf: 'PDF',
    sessionStats: 'सेशन आकडेवारी',
    totalSessions: 'एकूण सेशन',
    inProgressSessions: 'चालू',
    avgDuration: 'सरासरी कालावधी',
    completionRate: 'पूर्णता',
    activePercentage: '% सक्रिय',
    lastSession: 'शेवट',
    noSessions: 'कोणतेही सेशन नाही',
    prakritidistribution: 'प्रकृती वितरण',
    gad7SeverityBreakdown: 'GAD-7 तीव्रता विश्लेषण',
    noPrakritiData: 'कोणताही प्रकृती डेटा उपलब्ध नाही',
    noGad7Data: 'कोणताही GAD-7 डेटा उपलब्ध नाही',
    dataExport: 'डेटा निर्यात',
    downloadCsv: 'CSV डाउनलोड करा',
    allSessionsScores: '- सर्व सेशन + स्कोर',
    exportToGoogleSheets: 'Google Sheets मध्ये निर्यात करा',
    comingSoon: '(लवकरच येत आहे)',
    generatePdfReport: 'PDF अहवाल व्युत्पन्न करा',
    downloadAssessmentReport: 'मूल्यांकन अहवाल डाउनलोड करा',
    backToResults: 'परिणामांवर परत या',
    generatingReport: 'अहवाल तयार होत आहे...',
    generatingReports: 'अहवाल तयार होत आहेत...',
    adminLogin: 'प्रशासक लॉगिन',
    username: 'वापरकर्ता नाव',
    password: 'पासवर्ड',
    enterUsername: 'आपले वापरकर्ता नाव प्रविष्ट करा',
    enterPassword: 'आपला पासवर्ड प्रविष्ट करा',
    loginFailed: 'लॉगिन अयोग्य',
    invalidCredentials: 'अवैध क्रेडेंशियल',
    loading: 'लोड होत आहे...',
    saving: 'जतन होत आहे...',
    exporting: 'निर्यात होत आहे...',
    starting: 'सुरु होत आहे...',
    error: 'त्रुटी',
    failedToLoad: 'लोड करणे अयोग्य',
    failedToSave: 'जतन करणे अयोग्य',
    tryAgain: 'पुन्हा प्रयत्न करा',
    sattvika: 'सात्विक',
    rajasika: 'राजसिक',
    tamasika: 'तामसिक',
  },
}

export function getLabel(key: keyof typeof UI_LABELS.EN, language: Language): string {
  return UI_LABELS[language]?.[key as any] || UI_LABELS.EN[key as any] || key
}

export function getLocalizedName(
  value: string,
  language: Language,
  type: 'severity' | 'category'
): string {
  const severityMap: Record<string, Record<Language, string>> = {
    MINIMAL: { EN: 'Minimal', HI: 'न्यूनतम', MR: 'किमान' },
    MILD: { EN: 'Mild', HI: 'हल्का', MR: 'हलका' },
    MODERATE: { EN: 'Moderate', HI: 'मध्यम', MR: 'मध्यम' },
    SEVERE: { EN: 'Severe', HI: 'गंभीर', MR: 'गंभीर' },
  }

  const categoryMap: Record<string, Record<Language, string>> = {
    SATTVIKA: { EN: 'Sattvika', HI: 'सात्विक', MR: 'सात्विक' },
    RAJASIKA: { EN: 'Rajasika', HI: 'राजसिक', MR: 'राजसिक' },
    TAMASIKA: { EN: 'Tamasika', HI: 'तामसिक', MR: 'तामसिक' },
  }

  if (type === 'severity') {
    return severityMap[value]?.[language] || value
  }
  if (type === 'category') {
    return categoryMap[value]?.[language] || value
  }

  return value
}
